### ISSUE TITLE
Some conerns about experimental settings

### ISSUE THREAD

**Issue by csyuhao** [zhmzm/FLAME#4]
Firstly, thanks to your implementation of FLAME for the research of backdoor attacks in FL.

When I read your implementation, I have a question about it: 
1) In 177 line of `main_fed.py`, it randomly chooses`attacker_number` malicious clients from chosen clients `m` per round. It means that in every round, there are fixed number of malicious clients participated in the aggregation process. It is a little unrealistic, isn't it? For example, in the implementation of `ksreenivasan` [1], it firstly initilizes a pool of malicious clients before lanching an attack, and then randomly selects `m` clients per round so that the number of malicious clients is dynamic.
I think his implentation is more realistic.

What's your oppion about this question?

[1] https://github.com/ksreenivasan/OOD_Federated_Learning

**Comment by zhmzm** [comment]
In the paper Sun Z, Kairouz P, Suresh A T, et al. Can you really backdoor federated learning?[J]. arXiv preprint arXiv:1911.07963, 2019, they discussed the difference between random sampling and fixed frequency attacks in the experiment section. In this repo, I implement fixed frequency attacks only. It is easy to adapt it to random sampling following my code.

**Comment by csyuhao** [comment]
Thanks a lot.
