### ISSUE TITLE
What does  the hyparameter-"tau" mean?

### ISSUE THREAD

**Issue by zalmanchen** [zhmzm/FLAME#5]
when I try to add "attack"(set the "proportion of mailicious clients" to 0.1 ), it shows the following error
![1697013213760](https://github.com/zhmzm/FLAME/assets/70104951/9c8ad47d-6951-4ed6-a8f7-7bec297d8ca3)

Then, I trace it and find the following code.
![56b263e9a49f19223f11d79203218a9](https://github.com/zhmzm/FLAME/assets/70104951/b3e6d343-ed10-47f0-ae6c-6c71684239ad)

**Comment by zhmzm** [comment]
Hi Zalman,

It is a hyperparameter introduced by our new [paper](https://openreview.net/forum?id=AJBGSVSTT2), which is not for FLAME. You can comment it.

**Comment by zalmanchen** [comment]
Thank you very much! 

And congratulations on your new paper！

**Comment by zhmzm** [comment]
Thanks! Feel free to contact me if you have any problems with this repo.
