### ISSUE TITLE
'Namespace' object has no attribute 'tau'

### ISSUE THREAD

**Issue by zhanz5** [zhmzm/FLAME#6]
info.append(f'    Attack tau: {args.tau}')
AttributeError: 'Namespace' object has no attribute 'tau'

**Comment by zhmzm** [comment]
Hi Jenson,

Thanks for your report. Just comment this line. Tau is introduced by our new [paper](https://openreview.net/forum?id=AJBGSVSTT2), instead of being utilized in FLAME.
